# Introduction to NUMPY

In [3]:
import numpy as np
import pandas as pd
 

In [31]:
kanto  = np.array([63,34,5,3])
weights  = np.array([67,23,78,90])


## dot product of 1-D array by numpy

In [40]:
np.dot(kanto,weights)



5663

## multiplication of 1-D array by numpy

In [41]:
kanto*weights


array([4221,  782,  390,  270])

## sum of 1-D array direct by numpy

In [36]:
(kanto *weights).sum()     ##same as dot product mention above

5663

# 2-D array in numpy

In [39]:
a = np.array([[2,4,5],
              [6,7,3],
              [23,12,56]])

### shape method -- gives the dimension of 2-D array

In [43]:
a.shape     

(3, 3)

In [44]:
a.dtype

dtype('int64')

In [45]:
a

array([[ 2,  4,  5],
       [ 6,  7,  3],
       [23, 12, 56]])

#### all elements in numpy have same data type which is not the case in python list

## matrix multipication in numpy
### use the operator "@" to direct multiplication
### and another method is to use "np.matmul(A, B)" expression

In [47]:
b = np.array([[ 2,  4,  5],
       [ 6,  7,  3],
       [23, 12, 56]])

In [48]:
a@b

array([[ 143,   96,  302],
       [ 123,  109,  219],
       [1406,  848, 3287]])

In [49]:
np.matmul(a,b)

array([[ 143,   96,  302],
       [ 123,  109,  219],
       [1406,  848, 3287]])

### SUM OF MATRIX

In [52]:
a+b

array([[  4,   8,  10],
       [ 12,  14,   6],
       [ 46,  24, 112]])

#### commmon operation

In [53]:
a+5

array([[ 7,  9, 10],
       [11, 12,  8],
       [28, 17, 61]])

In [54]:
a/2

array([[ 1. ,  2. ,  2.5],
       [ 3. ,  3.5,  1.5],
       [11.5,  6. , 28. ]])

#### for addition if rows are not same in two matrix still numpy do addition
#### but columns has to be same otherwise error

In [58]:
 arr = np.array( [4,34,6])

In [59]:
b+arr

array([[ 6, 38, 11],
       [10, 41,  9],
       [27, 46, 62]])

### numpy supports comparision operators

In [60]:
a==b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### we can directly download a txt file by using a URL adress of the file
#### by using the "urllib" library as----
####  1-  import urllib as ulb
####  2-  urllib.request.retrieve('link' , 'filename.txt')
####  3-  then run and txt will download
####   in next cell covert the txt into 2D array as----
#### 1- variablename = np.genfromtxt('filename.txt', delimiter= 'enter the symbol by which columns are separated in the txtfile' , skip_header="enter the row you want skip")
####    run the cell

### Concatenate two 2D array
#### variable_name = np.concatenate( (A,B) , axis ="if columnwise use "1" and for rowwise use "0")

### Saving txt file after making changes
#### np.savetxt('modifyfilename.txt',
####             modifyfilename,
####             fmt = '%.2f',
####             header = ' 'coloumn1' , 'coloumn2' ,'coloumn3','coloumn4' .....
####             comments =''          )

In [29]:
arr = np.array([4,5,6] , np.int64)         ## np.int64 tells the dtype of the element means memory allocated to each element in array

In [38]:
arr[2]

6

In [39]:
arr.dtype

dtype('int64')

### other methods in numpy

In [40]:
zero = np.zeros(5)           ## create array of size 5 with all zeros

In [41]:
zero

array([0., 0., 0., 0., 0.])

In [43]:
rng = np.arange(10)       ## give numpy array of numbers from 0 to 9

In [45]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
apl = np.linspace(1,10, 6)     ## gives only 6 numbers follows an AP sequence in range of 1 to 10.

In [51]:
apl

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [61]:
randm = np.empty((1,5))           ## gives a random array of given shape like (1,5)

In [62]:
randm

array([[4.67762971e-310, 0.00000000e+000, 6.94316149e-310,
        4.67762937e-310, 0.00000000e+000]])

In [64]:
ide  = np.identity(5)     ### gives an identity array of shape (5,5)

In [65]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
ide.shape

(5, 5)

## Numpy axis
### for 1D only one axis i.e axis =0
### for 2D two axis i.e. axis =1, axis =0     (0 for rows and 1 for coloums)

In [68]:
ll = np.array([[2,3,4],[5,2,1],[84,2,8]])

In [71]:
ll.sum(axis = 0)       ## sum across rows

array([91,  7, 13])

In [72]:
ll.sum(axis = 1)  ### sum across coloums

array([ 9,  8, 94])

In [74]:
ll.T          ### gives the transpose of numpy array

array([[ 2,  5, 84],
       [ 3,  2,  2],
       [ 4,  1,  8]])

In [75]:
ll.ndim      ### gives the dimension of numpy array

2

In [81]:
### argmin() and argmax gives index of minimum and maximum
ar = np.array([3,4,5,645,-2,78])
ar.argmax()    
ar.argmin()        ## you can pass axis to find max or min in a row or coloumn

4

In [82]:
## argsort()     gives the array of index of sorted element 
ar.argsort()

array([4, 0, 1, 2, 5, 3])

In [83]:
### reshape((a,b)) gives array of shape (a,b)    

In [84]:
ar.reshape((6,1))

array([[  3],
       [  4],
       [  5],
       [645],
       [ -2],
       [ 78]])

In [85]:
ar.reshape((6,))

array([  3,   4,   5, 645,  -2,  78])

In [87]:
### np.where(condition) gives the location of elements satisfy the condition

np.where(ll>2)

(array([0, 0, 1, 2, 2]), array([1, 2, 0, 0, 2]))

In [89]:
### np.count_nonzero("list")   gives numbers of non-zero

np.count_nonzero(ar)

6

# more methods can be found on SciPy.org

# ~ Aditya Mathur